const theme = {
  ltr: "text-left",
  rtl: "text-right",
  placeholder: "editor-placeholder",
  paragraph: "mb-2 text-zinc-700 leading-7",
  quote: "pl-4 border-l-4 border-zinc-300 italic text-zinc-600 my-4",
  heading: {
    h1: "scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl mb-4 mt-6 text-zinc-900",
    h2: "scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0 mb-4 mt-6 text-zinc-900",
    h3: "scroll-m-20 text-2xl font-semibold tracking-tight mb-2 mt-4 text-zinc-900",
  },
  list: {
    nested: {
      listitem: "pl-6",
    },
    ol: "list-decimal pl-6 mb-4 text-zinc-700",
    ul: "list-disc pl-6 mb-4 text-zinc-700",
    listitem: "pl-1",
  },
  image: "cursor-default inline-block relative select-none",
  link: "font-medium text-blue-600 underline underline-offset-4 cursor-pointer",
  text: {
    bold: "font-bold text-zinc-900",
    italic: "italic",
    underline: "underline underline-offset-4",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "relative rounded bg-zinc-100 px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold text-zinc-900 border border-zinc-200",
  },
  code: "relative rounded bg-zinc-950 px-4 py-4 font-mono text-sm text-zinc-50 my-4 block overflow-x-auto",
  codeHighlight: {
    atrule: "text-[#c792ea]",
    attr: "text-[#ffcb6b]",
    boolean: "text-[#ff5874]",
    builtin: "text-[#82aaff]",
    cdata: "text-[#80cbc4]",
    char: "text-[#d6deeb]",
    class: "text-[#ffcb6b]",
    "class-name": "text-[#f2ff00]",
    comment: "text-[#637777]",
    constant: "text-[#82aaff]",
    deleted: "text-[#ff5874]",
    doctype: "text-[#637777]",
    entity: "text-[#82aaff]",
    function: "text-[#82aaff]",
    important: "text-[#d6deeb]",
    inserted: "text-[#addb67]",
    keyword: "text-[#c792ea]",
    namespace: "text-[#d6deeb]",
    number: "text-[#f78c6c]",
    operator: "text-[#89ddff]",
    prolog: "text-[#637777]",
    property: "text-[#80cbc4]",
    punctuation: "text-[#89ddff]",
    regex: "text-[#d6deeb]",
    selector: "text-[#c792ea]",
    string: "text-[#ecc48d]",
    symbol: "text-[#addb67]",
    tag: "text-[#7fdbca]",
    url: "text-[#addb67]",
    variable: "text-[#d6deeb]",
  },
};

export default theme;